language: php

matrix:
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0

install: composer install $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - '[[ $USE_COVERAGE != "1" ]] || ./vendor/bin/php-coveralls --verbose'

branches:
  only:
    - master
